import { useEffect, useRef, useState } from 'react';
import { ChevronLeft, ChevronRight, Plus, RefreshCw, X } from 'lucide-react';
import type { Actor } from '../../../shared/auth';
import { decimalMoney, type MasterHistory, type MasterList, type MasterRecord, type Resource } from '../../../shared/master-data';
import { listRecords, masterConfig } from './master-config';
import { MasterDialog } from './MasterDialog';

export function MasterPage({ user, initial, onUnauthorized }: { user: Actor; initial: Resource; onUnauthorized(): void }) {
  const available: Resource[] = initial === 'areas' ? ['areas','collectors'] : user.permissions.includes('subscriber.view') ? ['subscribers','services','plans'] : ['services','plans'];
  const [resource,setResource] = useState(initial); const [query,setQuery] = useState(''); const [status,setStatus] = useState(''); const [sort,setSort] = useState<'code' | 'name'>('code'); const [direction,setDirection] = useState<'asc' | 'desc'>('asc'); const [page,setPage] = useState(1); const [revision,setRevision] = useState(0);
  const [data,setData] = useState<MasterList | null>(null); const [loading,setLoading] = useState(true); const [error,setError] = useState(''); const [notice,setNotice] = useState('');
  const [dialog,setDialog] = useState<{ record: MasterRecord | null; mode: 'edit' | 'view' | 'assign' } | null>(null); const [history,setHistory] = useState<MasterRecord | null>(null);
  const config = masterConfig[resource]; const canWrite = user.permissions.includes(config.permission); const canAssign = ['subscribers','services'].includes(resource) && user.permissions.includes('collection.manage');
  useEffect(() => {
    let current = true; setLoading(true); setError('');
    const timer = setTimeout(() => { void listRecords(resource,{ q: query, page, sort, direction, ...(status ? { status } : {}) }).then(result => {
      if (!current) return;
      if (result.ok) setData(result.data); else { setData(null); setError(result.error.message); if (result.error.status === 401) onUnauthorized(); }
    }).catch(() => { if (current) { setData(null); setError('Unable to load records. Refresh to try again.'); } }).finally(() => { if (current) setLoading(false); }); },180);
    return () => { current = false; clearTimeout(timer); };
  },[resource,query,status,sort,direction,page,revision]);
  function switchResource(value: Resource) { setResource(value); setQuery(''); setStatus(''); setSort('code'); setPage(1); setData(null); setNotice(''); }
  const states = resource === 'services' ? ['PENDING','ACTIVE','INACTIVE','TERMINATED','ARCHIVED'] : resource === 'subscribers' ? ['ACTIVE','INACTIVE','TERMINATED','ARCHIVED'] : ['ACTIVE','INACTIVE'];
  return <div className="master-page"><div className="module-tabs" role="tablist" aria-label="Account maintenance">{available.map(value => <button role="tab" aria-selected={resource === value} key={value} onClick={() => switchResource(value)}>{masterConfig[value].title}</button>)}</div>
    <div className="page-heading"><div><p className="eyebrow">{initial === 'areas' ? 'COLLECTION SETUP' : 'PEOPLE & SUBSCRIPTIONS'}</p><h1>{config.title}</h1><p className="muted">{resource === 'plans' ? 'Maintain service offers. Previous revisions and assigned rates are retained.' : resource === 'services' ? 'Manage installation details, service status and explicit billing rates.' : 'Search, maintain and review records without deleting their history.'}</p></div>{canWrite && <button className="primary-button" onClick={() => setDialog({ record: null, mode: 'edit' })}><Plus size={16}/>New {config.singular}</button>}</div>
    <div className="master-toolbar"><input aria-label="Search records" placeholder={resource === 'subscribers' ? 'Account, name, contact or address…' : 'Search code, name or address…'} value={query} onChange={event => { setQuery(event.target.value); setPage(1); }}/><select aria-label="Filter status" value={status} onChange={event => { setStatus(event.target.value); setPage(1); }}><option value="">All statuses</option>{states.map(value => <option key={value}>{value}</option>)}</select><select aria-label="Sort records" value={sort} onChange={event => { setSort(event.target.value as 'code' | 'name'); setPage(1); }}><option value="code">Account / code</option>{resource !== 'services' && <option value="name">Name</option>}</select><button className="refresh-button" aria-label="Reverse sort order" onClick={() => setDirection(value => value === 'asc' ? 'desc' : 'asc')}>{direction === 'asc' ? 'A–Z' : 'Z–A'}</button><button className="refresh-button" disabled={loading} onClick={() => setRevision(value => value+1)}><RefreshCw size={14}/>Refresh</button></div>
    {error && <div className="form-alert" role="alert">{error}</div>}{notice && <div className="success-notice" role="status">{notice}</div>}
    <section className="users-table-panel" aria-busy={loading}><header><h2>{data?.total ?? 0} records</h2><span className="muted">Page {page} of {Math.max(1,Math.ceil((data?.total ?? 0)/20))}</span></header>
      {loading ? <p className="table-state" role="status">Loading records…</p> : <div className="table-scroll"><table><thead><tr><th>Account / code</th><th>{resource === 'services' ? 'Installation address' : 'Name'}</th><th>{resource === 'plans' || resource === 'services' ? 'Monthly rate' : 'Contact / details'}</th><th>Status</th><th>Actions</th></tr></thead><tbody>{data?.items.map(row => <tr key={row.id}><td>{row.code}</td><td>{'name' in row ? row.name : row.installationAddress}</td><td className={resource === 'plans' || resource === 'services' ? 'money-cell' : ''}>{'priceCentavos' in row ? `PHP ${decimalMoney(row.priceCentavos)}` : 'currentRateCentavos' in row ? `PHP ${decimalMoney(row.currentRateCentavos)}` : 'contact' in row ? row.contact || '—' : 'description' in row ? row.description || '—' : '—'}</td><td><span className={`badge ${('active' in row ? row.active : row.status === 'ACTIVE') ? 'good' : 'neutral'}`}>{'active' in row ? row.active ? 'ACTIVE' : 'INACTIVE' : row.status}</span></td><td><div className="row-actions"><button className="text-button" aria-label={`${canWrite ? 'Edit' : 'View'} ${row.code}`} onClick={() => setDialog({ record: row, mode: canWrite ? 'edit' : 'view' })}>{canWrite ? 'Edit' : 'View'}</button>{canAssign && !canWrite && <button className="text-button" aria-label={`Assign ${row.code}`} onClick={() => setDialog({ record: row, mode: 'assign' })}>Assign</button>}<button className="text-button" aria-label={`History ${row.code}`} onClick={() => setHistory(row)}>History</button></div></td></tr>)}</tbody></table>{data?.items.length === 0 && <p className="table-state">No matching records. Try another search or create a record.</p>}</div>}
      <footer><span>History is retained for every saved revision.</span><div><button className="icon-button" aria-label="Previous page" disabled={loading || page <= 1} onClick={() => setPage(value => value-1)}><ChevronLeft size={16}/></button><button className="icon-button" aria-label="Next page" disabled={loading || page*20 >= (data?.total ?? 0)} onClick={() => setPage(value => value+1)}><ChevronRight size={16}/></button></div></footer></section>
    <p className="info-note">{resource === 'services' ? 'Review a service account before changing its status or billing rate.' : resource === 'subscribers' ? 'Archive or terminate accounts to preserve history. Deactivate active services first.' : initial === 'areas' ? 'Keep collection areas and collector assignments current before preparing routes.' : 'Price changes apply to new assignments. Update existing service rates separately.'}</p>
    {dialog && <MasterDialog resource={resource} record={dialog.record} mode={dialog.mode} onClose={() => setDialog(null)} onSaved={() => { setDialog(null); setNotice('Record saved.'); setRevision(value => value+1); }} onUnauthorized={onUnauthorized}/>}
    {history && <HistoryDialog resource={resource} record={history} onClose={() => setHistory(null)} onUnauthorized={onUnauthorized}/>}
  </div>;
}

function HistoryDialog({ resource, record, onClose, onUnauthorized }: { resource: Resource; record: MasterRecord; onClose(): void; onUnauthorized(): void }) {
  const dialog = useRef<HTMLDialogElement>(null); const [data,setData] = useState<MasterHistory | null>(null); const [error,setError] = useState(''); const [page,setPage] = useState(1);
  useEffect(() => { dialog.current?.showModal(); },[]);
  useEffect(() => { let current = true; setData(null); setError(''); void window.bcis.getMasterHistory(resource,record.id,page).then(result => { if (!current) return; if (result.ok) setData(result.data); else { setError(result.error.message); if (result.error.status === 401) onUnauthorized(); } }).catch(() => { if (current) setError('History could not be loaded.'); }); return () => { current = false; }; },[resource,record.id,page]);
  return <dialog className="account-dialog master-dialog" ref={dialog} aria-labelledby="history-title" onCancel={event => { event.preventDefault(); onClose(); }}><header><h2 id="history-title">History · {record.code}</h2><button className="icon-button" aria-label="Close history" onClick={onClose}><X size={18}/></button></header>{error && <div role="alert">{error}</div>}{!data && !error && <p role="status">Loading history…</p>}<div className="history-list">{data?.items.map(item => <details key={item.version}><summary><strong>Revision {item.version}</strong> · {new Date(item.createdAt).toLocaleString()} · {item.actorName}<p>{item.reason}</p></summary><dl>{masterConfig[resource].fields.map(field => <div key={field.key}><dt>{field.label}</dt><dd>{field.type === 'money' ? `PHP ${decimalMoney(item.snapshot[field.key] as number)}` : Array.isArray(item.snapshot[field.key]) ? (item.snapshot[field.key] as string[]).join('; ') : String(item.snapshot[field.key] ?? 'Unassigned')}</dd></div>)}</dl></details>)}</div><footer className="history-footer"><button className="refresh-button" disabled={page <= 1 || !data} onClick={() => setPage(value => value-1)}>Previous</button><span>Page {page}</span><button className="refresh-button" disabled={!data || page*20 >= data.total} onClick={() => setPage(value => value+1)}>Next</button></footer></dialog>;
}
