import { contextBridge, ipcRenderer } from 'electron';
import type { DesktopBridge } from '../../shared/contracts';

const bridge: DesktopBridge = {
  listPlans: (input) => ipcRenderer.invoke('bcis:list-plans',input),
  savePlan: (id,input) => ipcRenderer.invoke('bcis:save-plan',id,input),
  listAreas: (input) => ipcRenderer.invoke('bcis:list-areas',input),
  saveArea: (id,input) => ipcRenderer.invoke('bcis:save-area',id,input),
  listCollectors: (input) => ipcRenderer.invoke('bcis:list-collectors',input),
  saveCollector: (id,input) => ipcRenderer.invoke('bcis:save-collector',id,input),
  listSubscribers: (input) => ipcRenderer.invoke('bcis:list-subscribers',input),
  saveSubscriber: (id,input) => ipcRenderer.invoke('bcis:save-subscriber',id,input),
  listServices: (input) => ipcRenderer.invoke('bcis:list-services',input),
  saveService: (id,input) => ipcRenderer.invoke('bcis:save-service',id,input),
  getMasterRecord: (resource,id) => ipcRenderer.invoke('bcis:get-master-record',resource,id),
  getMasterHistory: (resource,id,page) => ipcRenderer.invoke('bcis:get-master-history',resource,id,page),
  assignSubscriber: (id,input) => ipcRenderer.invoke('bcis:assign-subscriber',id,input),
  assignService: (id,input) => ipcRenderer.invoke('bcis:assign-service',id,input),
  getSystemStatus: () => ipcRenderer.invoke('bcis:get-system-status'),
  login: (input) => ipcRenderer.invoke('bcis:login', input),
  getSession: () => ipcRenderer.invoke('bcis:get-session'),
  logout: () => ipcRenderer.invoke('bcis:logout'),
  lock: () => ipcRenderer.invoke('bcis:lock'),
  listUsers: (page) => ipcRenderer.invoke('bcis:list-users', page),
  createUser: (input) => ipcRenderer.invoke('bcis:create-user', input),
  updateUser: (id, input) => ipcRenderer.invoke('bcis:update-user', id, input),
  listBillingCycles: () => ipcRenderer.invoke('bcis:list-billing-cycles'),
  listBillingRuns: (page) => ipcRenderer.invoke('bcis:list-billing-runs', page),
  generateBillingRun: (input) => ipcRenderer.invoke('bcis:generate-billing-run', input),
  listBillingInvoices: (query) => ipcRenderer.invoke('bcis:list-billing-invoices', query),
  getBillingInvoice: (id) => ipcRenderer.invoke('bcis:get-billing-invoice', id),
  createBillingInvoice: (input) => ipcRenderer.invoke('bcis:create-billing-invoice', input),
  replaceBillingInvoiceItems: (id, input) => ipcRenderer.invoke('bcis:replace-billing-invoice-items', id, input),
  finalizeBillingInvoice: (id, input) => ipcRenderer.invoke('bcis:finalize-billing-invoice', id, input),
  adjustBillingInvoice: (id, input) => ipcRenderer.invoke('bcis:adjust-billing-invoice', id, input),
  voidBillingInvoice: (id, input) => ipcRenderer.invoke('bcis:void-billing-invoice', id, input),
  sweepOverdueInvoices: (input) => ipcRenderer.invoke('bcis:sweep-overdue-invoices', input),
  getSubscriberLedger: (query) => ipcRenderer.invoke('bcis:get-subscriber-ledger', query),
  listPayments: (query) => ipcRenderer.invoke('bcis:list-payments', query),
  getPayment: (id) => ipcRenderer.invoke('bcis:get-payment', id),
  getSubscriberAccount: (subscriberId) => ipcRenderer.invoke('bcis:get-subscriber-account', subscriberId),
  getPaymentProof: (id) => ipcRenderer.invoke('bcis:get-payment-proof', id),
  recordPayment: (input) => ipcRenderer.invoke('bcis:record-payment', input),
  verifyPayment: (id, input) => ipcRenderer.invoke('bcis:verify-payment', id, input),
  voidPayment: (id, input) => ipcRenderer.invoke('bcis:void-payment', id, input),
  reversePayment: (id, input) => ipcRenderer.invoke('bcis:reverse-payment', id, input),
  listCollectionBatches: (query) => ipcRenderer.invoke('bcis:list-collection-batches', query),
  getCollectionBatch: (id) => ipcRenderer.invoke('bcis:get-collection-batch', id),
  getCollectionRouteSheet: (id) => ipcRenderer.invoke('bcis:get-collection-route-sheet', id),
  createCollectionBatch: (input) => ipcRenderer.invoke('bcis:create-collection-batch', input),
  startCollectionBatch: (id) => ipcRenderer.invoke('bcis:start-collection-batch', id),
  submitCollectionBatch: (id, input) => ipcRenderer.invoke('bcis:submit-collection-batch', id, input),
  remitCollectionBatch: (id, input) => ipcRenderer.invoke('bcis:remit-collection-batch', id, input),
  reconcileCollectionBatch: (id, input) => ipcRenderer.invoke('bcis:reconcile-collection-batch', id, input),
  closeCollectionBatch: (id, input) => ipcRenderer.invoke('bcis:close-collection-batch', id, input),
};
contextBridge.exposeInMainWorld('bcis', bridge);
