import { describe, expect, it } from 'vitest';
import { readFileSync, readdirSync } from 'node:fs';
import { resolve } from 'node:path';
import { isTrustedRendererUrl } from '../../source/desktop/main/renderer-security';

describe('trusted renderer URL', () => {
  it('accepts the canonical trailing slash Chromium adds to the development origin', () => {
    expect(isTrustedRendererUrl('http://localhost:5173/', 'http://localhost:5173')).toBe(true);
  });
  it.each(['http://localhost:5174/', 'http://localhost:5173/other', 'https://example.com/', 'not-a-url'])('rejects a different page %s', (actual) => {
    expect(isTrustedRendererUrl(actual, 'http://localhost:5173')).toBe(false);
  });
});

describe('the reports screen renderer', () => {
  const rendererDir = resolve(process.cwd(), 'source/desktop/renderer');
  // Every renderer source file is read, not just the report page: the rules below are about
  // what the renderer process is allowed to reach, and a second file could open that door.
  const source = readdirSync(rendererDir, { recursive: true, encoding: 'utf8' })
    .filter(name => /\.(ts|tsx)$/.test(name))
    .map(name => readFileSync(resolve(rendererDir, name), 'utf8'))
    .join('\n');

  it('gives the renderer no way to read or write a file of its own', () => {
    // Every report document is produced by the API and written by the main process. A
    // renderer that could name a path, receive bytes or call a filesystem API would turn a
    // read-only reporting screen into an arbitrary file read and write.
    expect(source).not.toMatch(/require\s*\(/);
    expect(source).not.toMatch(/from\s+['"]node:/);
    expect(source).not.toMatch(/\bfetch\b/);
    expect(source).not.toMatch(/readFile|writeFile|fs\.|electron/);
    // window.bcis is the only capability the renderer has, and it is typed to these methods.
    expect(source).not.toMatch(/bcis\.\w*Export|exportDocument|saveTo/);
  });

  it('asks for documents instead of assembling them', () => {
    // The official receipt is a document the API renders from the allocation it posted. A
    // renderer that built one from the payment record would be a second, unaudited copy of a
    // financial document, and the copy the customer keeps would have no record of being issued.
    // A payment proof may legitimately be previewed inline as a data URL: that is an image the
    // customer sent in, not a document the office issues. What must never happen is one being
    // built to stand in for the official receipt, so the check is on the print path itself.
    expect(source).toMatch(/printReceipt/);
    expect(source).not.toMatch(/printReceipt[\s\S]{0,400}?(data:application\/pdf|base64,)/);
    // The receipt preview still only ever points at the stored proof, never at generated bytes.
    expect(source).not.toMatch(/printReceipt\(\s*\)\s*;?\s*[^]*?window\.bcis\.[a-zA-Z]*[Rr]ender/);
    // It must not offer a format or a file name, which would let the renderer and the server
    // disagree about what was printed.
    expect(source).not.toMatch(/printReceipt\([^)]*,\s*['"](?:PDF|XLSX|CSV)['"]/);
    expect(source).not.toMatch(/printReceipt\([^)]*fileName/);
  });

  it('never computes a total, a balance or an aging bucket in the renderer', () => {
    // Every peso shown here arrived from the API as integer centavos. A renderer-side sum
    // would be a second opinion about money that the tests above cannot check against the
    // database, and it could disagree with the report it is meant to display.
    expect(source).not.toMatch(/\.reduce\(\s*\([^)]*Centavos[^)]*\)\s*=>[^)]*\+/);
    expect(source).not.toMatch(/reduce\([\s\S]{0,120}?Centavos[\s\S]{0,120}?\+[\s\S]{0,40}?Centavos/);
    // Dividing centavos to make pesos is the rounding bug this project avoids throughout.
    expect(source).not.toMatch(/Centavos\s*\/\s*100/);
  });

  it('lets the renderer ask for a backup but never reach one', () => {
    // The archive holds every subscriber record and every posted payment, so it is the most
    // sensitive file the system produces. The desktop may ask the server to take one, verify one
    // or restore one, and may show what came back; it must not be able to name a file, receive
    // bytes, or delete or move an archive.
    expect(source).toMatch(/createBackup/);
    expect(source).toMatch(/verifyBackup/);
    expect(source).toMatch(/restoreBackup/);
    // No backup operation takes a path, a folder or an archive name. The storage directory the
    // server reports is displayed as text and is never passed back into another call.
    expect(source).not.toMatch(/(?:createBackup|verifyBackup|restoreBackup)\([^)]*(?:path|folder|directory|fileName)\s*[=:]/i);
    expect(source).not.toMatch(/(?:createBackup|verifyBackup|restoreBackup)\([^)]*['"][A-Za-z]:\\\\/);
    // Nothing brings the archive itself across the bridge.
    expect(source).not.toMatch(/(?:createBackup|verifyBackup|restoreBackup|listBackups)\([\s\S]{0,400}?(?:data:application\/octet-stream|base64,|ArrayBuffer)/);
    // And a restore still requires the confirmation word and a reason, so the screen cannot be
    // used to skip the part of the decision that asks the operator to mean it.
    expect(source).toMatch(/confirm\s*!==\s*'RESTORE'|confirm\s*===\s*'RESTORE'/);
  });
});
